### ISSUE TITLE
Zelda Twilight Princess Animation Import Failure

### ISSUE THREAD

**Issue by GANONdork123** [niacdoial/blemd#8]
The animations for models in the Legend of Zelda: Twilight Princess do not appear to import correctly, and some models (such as Link's) will cause Blender to crash while attempting to open if the animation files are present.
![image](https://user-images.githubusercontent.com/20745330/29245639-98999454-7fae-11e7-90f7-4f3230b9fce7.png)

Otherwise, Twilight Princess models import just fine.

**Comment by niacdoial** [comment]
hello, and sorry for answering so late, I was without my computer for a while.
Can I ask you to give me some of the files that caused this problem (and possibly the settings used), please?
it will be far easier to correct it like with them.
(also please note than the animation files in a "bck" folder may correspond to any model from the neighboring "bmdr"/"bmdv" folder, it may be the couse of the problem)

**Comment by GANONdork123** [comment]
Sure here you go.  [Maro (model in the screenshot)](https://drive.google.com/open?id=0B56Qal6OWVkoSlEwQm1tNlFLcU0), [Kmdl (Link)](https://drive.google.com/open?id=0B56Qal6OWVkodkFFcTk0VEJKcmc)

**Comment by niacdoial** [comment]
Thanks.
I started working on it.
I will tell you when it is fixed.

**Comment by niacdoial** [comment]
fixed what seems to be half of the issue
results looks like a badly broken human instead of an amorphous blob
other half continues to be out of sight.
trying to isolate parts of the code

**Comment by niacdoial** [comment]
Commited what worked on my side.
Does it work on yours?

**Comment by GANONdork123** [comment]
Maro.bmd imports perfectly with animations, however al.bmd still fails to import when trying to import with animations.

**Comment by niacdoial** [comment]
I'll work on it, but I have to tell you that I can't give it nearly as much time as before.

**Comment by GANONdork123** [comment]
I've found another oddity. It seems Twilight Princess has different kinds of BMD models. BleMD can import BMDs if the folder they are in when dumped is called "bmde" or "bmwr" but sometimes Blender crashes when trying to import BMDs from a "bmdr" folder, so there must be something different between the BMDs inside those folders. [https://drive.google.com/open?id=0B56Qal6OWVkobkhEeWh1OUFDNTg](here's an archive of each of the different types). The "bmdr" one refuses to import.

**Comment by niacdoial** [comment]
Fixed the previously mentioned crash.
it also seems that it is more stable if animations are imported in small groups.
to exclude animations, you can move the corresponding `.bck` files, or change their extension.
I also just read your new message.

**Comment by GANONdork123** [comment]
OK it seems all BMDs import, however the ones used for Maps take an exceptionally long time, and vertex colors and normals are lost. Blender also gives an error similar to this.

![image](https://user-images.githubusercontent.com/20745330/33801131-f99cb128-dd1e-11e7-8343-8bd3ecadef7d.png)

**Comment by niacdoial** [comment]
Could I have the files that caused this crash (and some with data loss),
please?
I'll try to work on it.
thanks

2017-12-10 2:25 GMT+01:00 GANONdork123 <notifications@github.com>:

**Comment by GANONdork123** [comment]
[R00_00.arc 0.rarc_dir.zip](https://github.com/niacdoial/blemd/files/1546291/R00_00.arc.0.rarc_dir.zip)
All of the ones used for level/map geometry seem to have the same issue.

**Comment by niacdoial** [comment]
There. It works on my side. Will close issue if it works on yours

**Comment by GANONdork123** [comment]
Seems to work perfectly now! If anything else comes up I'll open another issue, but until then it seems to work perfectly.

**Comment by niacdoial** [comment]
Ok!
PS: The image loader broke, but it only made the thing crash when importing a model for the first time. Fixed it now.
